export const ADD_PROJECT = 'ADD_PROJECT'
export const CHANGE_PROJECT = 'CHANGE_PROJECT'
export const REMOVE_PROJECT = 'REMOVE_PROJECT'
export const DEFINE_PROJECTS = 'DEFINE_PROJECTS'

export const NOTIFY = 'NOTIFY'